import { route, type ClientRouteDefinition } from "../route-types";

export const CALCULATOR_ROUTES = [
  route("/calculators/income-tax", "calculator", "client/src/features/calculators/pages/income-tax.page.tsx"),
  route("/calculators/tax-regime", "calculator", "client/src/features/calculators/pages/tax-regime.page.tsx"),
  route("/calculators/hra", "calculator", "client/src/features/calculators/pages/hra.page.tsx"),
  route("/calculators/sip", "calculator", "client/src/features/calculators/pages/sip.page.tsx"),
  route("/calculators/sip-enhanced", "calculator", "client/src/features/calculators/pages/sip-enhanced.page.tsx"),
  route("/calculators/emi", "calculator", "client/src/features/calculators/pages/emi.page.tsx"),
  route("/calculators/tds", "calculator", "client/src/features/calculators/pages/tds.page.tsx"),
  route("/calculators/fd", "calculator", "client/src/features/calculators/pages/fd.page.tsx"),
  route("/calculators/fd-enhanced", "calculator", "client/src/features/calculators/pages/fd-enhanced.page.tsx"),
  route("/calculators/ppf", "calculator", "client/src/features/calculators/pages/ppf.page.tsx"),
  route("/calculators/withdrawal-planner", "calculator", "client/src/features/calculators/pages/withdrawal-planner.page.tsx"),
  route("/calculators/capital-gains", "calculator", "client/src/features/calculators/pages/capital-gains.page.tsx"),
  route("/calculators/home-loan", "calculator", "client/src/features/calculators/pages/loan-calculator.page.tsx"),
  route("/calculators/car-loan", "calculator", "client/src/features/calculators/pages/loan-calculator.page.tsx"),
  route("/calculators/personal-loan", "calculator", "client/src/features/calculators/pages/loan-calculator.page.tsx"),
  route("/calculators/education-loan", "calculator", "client/src/features/calculators/pages/loan-calculator.page.tsx"),
  route("/calculators", "calculator", "client/src/features/calculators/pages/index.page.tsx"),
  route("/calculators/regime-comparator", "calculator", "client/src/features/calculators/pages/tax-regime.page.tsx"),
  route("/calculators/advance-tax", "calculator", "client/src/features/calculators/pages/advance-tax.page.tsx"),
  route("/calculators/general", "calculator", "client/src/features/calculators/pages/general.page.tsx"),
  route("/calculators/hsn-finder", "calculator", "client/src/features/calculators/pages/hsn-finder.page.tsx"),
  route("/calculators/gst", "calculator", "client/src/features/calculators/pages/gst.page.tsx"),
  route("/calculators/salary", "calculator", "client/src/features/calculators/pages/salary.page.tsx"),
  route("/calculators/gratuity", "calculator", "client/src/features/calculators/pages/gratuity.page.tsx"),
  route("/calculators/epf", "calculator", "client/src/features/calculators/pages/epf.page.tsx"),
  route("/calculators/rd", "calculator", "client/src/features/calculators/pages/rd.page.tsx"),
  route("/calculators/lumpsum", "calculator", "client/src/features/calculators/pages/lumpsum.page.tsx"),
  route("/calculators/swp", "calculator", "client/src/features/calculators/pages/swp.page.tsx"),
  route("/calculators/inflation", "calculator", "client/src/features/calculators/pages/inflation.page.tsx"),
  route("/calculators/loan-eligibility", "calculator", "client/src/features/calculators/pages/loan-eligibility.page.tsx"),
  route("/calculators/nps", "calculator", "client/src/features/calculators/pages/nps.page.tsx"),
  route("/calculators/penalty", "calculator", "client/src/features/calculators/pages/penalty-calculator.page.tsx"),
  route("/calculators/:slug", "calculator", "client/src/pages/calculators/generated-calculator-info.page.tsx"),
] as const satisfies readonly ClientRouteDefinition[];
