import { route, type ClientRouteDefinition } from "../route-types";

export const CONTENT_ROUTES = [
  route("/learn/investment-basics", "content", "client/src/pages/learn/index.page.tsx"),
  route("/learn", "content", "client/src/pages/learn/index.page.tsx"),
  route("/learn/glossary", "content", "client/src/pages/learn/glossary.page.tsx"),
  route("/learn/videos", "content", "client/src/pages/learn/videos.page.tsx"),
  route("/learn/guides", "content", "client/src/pages/learn/guides.page.tsx"),
  route("/learn/guide/:slug", "content", "client/src/pages/learn/guide/[slug].page.tsx"),
  route("/learn/consultations", "content", "client/src/pages/learn/consultations.page.tsx"),
  route("/experts", "content", "client/src/pages/experts/index.page.tsx"),
  route("/experts/:id", "content", "client/src/pages/experts/profile.page.tsx"),
  route("/profiles", "content", "client/src/pages/profiles.page.tsx"),
  route("/which-itr-form-to-file", "content", "client/src/features/itr/pages/start.page.tsx"),
  route("/itr/form-selector", "content", "client/src/features/itr/pages/form-selector.page.tsx"),
  route("/itr/form-recommender", "content", "client/src/features/itr/pages/form-recommender.page.tsx"),
  route("/itr/success", "content", "client/src/features/itr/pages/success.page.tsx"),
  route("/itr/step-by-step-guide", "content", "client/src/features/itr/pages/step-by-step-guide.page.tsx"),
  route("/itr/compact-filing", "content", "client/src/features/itr/pages/compact-filing-guide.page.tsx"),
  route("/search", "content", "client/src/pages/search.page.tsx"),
  route("/itr-season-2026", "content", "client/src/pages/itr-season-campaign.page.tsx"),
  route("/itr-season-2026/:slug", "content", "client/src/pages/itr-season-campaign.page.tsx"),
  route("/partners", "content", "client/src/pages/partners.page.tsx"),
  route("/blog", "content", "client/src/pages/blog.page.tsx"),
  route("/blog/:slug", "content", "client/src/pages/blog/[slug].page.tsx"),
  route("/legal/privacy-policy", "content", "client/src/pages/legal/privacy-policy.page.tsx"),
  route("/legal/terms-of-service", "content", "client/src/pages/legal/terms-of-service.page.tsx"),
  route("/legal/refund-policy", "content", "client/src/pages/legal/refund-policy.page.tsx"),
  route("/legal/disclaimer", "content", "client/src/pages/legal/disclaimer.page.tsx"),
  route("/compliance-calendar", "content", "client/src/pages/compliance-calendar.page.tsx"),
  route("/expert-consultation", "content", "client/src/pages/expert-consultation.page.tsx"),
  route("/consultation", "content", "client/src/pages/expert-consultation.page.tsx"),
  route("/help", "content", "client/src/pages/help/help-center.page.tsx"),
  route("/help/faq", "content", "client/src/pages/help/faq.page.tsx"),
  route("/help/user-guide", "content", "client/src/pages/help/user-guide.page.tsx"),
  route("/help/knowledge-base", "content", "client/src/pages/help/knowledge-base.page.tsx"),
  route("/advanced-features", "content", "client/src/pages/advanced-features.page.tsx"),
  route("/compare", "content", "client/src/components/comparison/ComparisonToolsPage.tsx"),
  route("/compare/:slug", "content", "client/src/pages/compare/competitor-comparison.page.tsx"),
] as const satisfies readonly ClientRouteDefinition[];
