import { route, type ClientRouteDefinition } from "../route-types";

export const SERVICE_ROUTES = [
  route("/services/selection", "service", "client/src/pages/services/selection.page.tsx"),
  route("/services/activate/:serviceId", "service", "client/src/pages/services/activation.page.tsx"),
  route("/services/marketplace", "service", "client/src/pages/services/marketplace.page.tsx"),
  route("/business/virtual-cfo", "service", "client/src/pages/business/virtual-cfo.page.tsx"),
  route("/services/notice-compliance", "service", "client/src/pages/services/notice-compliance.page.tsx"),
  route("/services/tds-filing", "service", "client/src/pages/services/tds-filing.page.tsx"),
  route("/itr-filing", "service", "client/src/pages/services/generated-service.page.tsx"),
  route("/gst-filing", "service", "client/src/pages/services/gst-returns.page.tsx"),
  route("/salary", "service", "client/src/pages/services/itr-for-salaried.page.tsx"),
  route("/services/itr-for-salaried", "service", "client/src/pages/services/itr-for-salaried.page.tsx"),
  route("/services/gst-registration", "service", "client/src/pages/services/gst-registration.page.tsx"),
  route("/services/company-registration", "service", "client/src/pages/services/company-registration.page.tsx"),
  route("/services/startup-india-registration", "service", "client/src/pages/services/startup-india-registration.page.tsx"),
  route("/startup/registration", "service", "client/src/pages/startup/registration.page.tsx"),
  route("/services/msme-udyam-registration", "service", "client/src/pages/services/msme-udyam-registration.page.tsx"),
  route("/services/fssai-registration", "service", "client/src/pages/services/fssai-registration.page.tsx"),
  route("/services/trade-license", "service", "client/src/pages/services/trade-license.page.tsx"),
  route("/services/company-incorporation", "service", "client/src/pages/services/company-registration.page.tsx"),
  route("/services/gst-returns", "service", "client/src/pages/services/gst-returns.page.tsx"),
  route("/services/trademark-registration", "service", "client/src/pages/services/trademark-registration.page.tsx"),
  route("/services/iso-certification", "service", "client/src/pages/services/iso-certification.page.tsx"),
  route("/services/labour-law-compliance", "service", "client/src/pages/services/labour-law-compliance.page.tsx"),
  route("/startup/funding", "service", "client/src/pages/startup/funding.page.tsx"),
  route("/startup/:slug", "service", "client/src/pages/startup/generated-startup-topic.page.tsx"),
  route("/startup-services", "service", "client/src/pages/startup-services.page.tsx"),
  route("/services/funding-assistance", "service", "client/src/pages/startup/funding.page.tsx"),
  route("/services/tax-planning", "service", "client/src/pages/services/tax-planning.page.tsx"),
  route("/services/compliance-management", "service", "client/src/pages/services/compliance-management.page.tsx"),
  route("/services/audit-services", "service", "client/src/pages/services/audit-services.page.tsx"),
  route("/services/document-vault", "service", "client/src/pages/services/document-vault.page.tsx"),
  route("/services/:slug", "service", "client/src/pages/services/generated-service.page.tsx"),
  route("/services/:service/:city", "service", "client/src/pages/services/city-landing.page.tsx"),
  route("/services", "service", "client/src/pages/services.page.tsx"),
  route("/all-services", "service", "client/src/pages/all-services.page.tsx"),
  route("/features/fastest-itr-filing", "service", "client/src/pages/features/fastest-itr-filing.page.tsx"),
  route("/features/tax-calculator", "service", "client/src/pages/features/tax-calculator.page.tsx"),
  route("/features/document-scanner", "service", "client/src/pages/features/document-scanner.page.tsx"),
  route("/features/expert-tax-review", "service", "client/src/pages/features/expert-tax-review.page.tsx"),
] as const satisfies readonly ClientRouteDefinition[];
