export const ayPersonaReviewNotes: Record<string, string> = {
  "ay-2026-27-architect-designer-44ada-itr-guide": `## Decide whether the engagement is design advice or a delivery contract

Read the scope and billing pattern before treating every receipt as professional fees. A drawing package, design consultation, site review, turnkey interior project, and resale of materials can place different demands on the working. Split invoices that combine design fees, reimbursable approvals, contractor payments, and products. Then bridge the gross client charge to GST records, Form 16A, and the net amount received after TDS. This prevents a large pass-through or material component from disappearing inside a single fee total.

Use that activity map to test the proposed return route. If the practice is considering presumptive treatment, document why the actual work fits the chosen approach and keep separately identifiable non-professional activity outside that conclusion. For project expenses, distinguish costs incurred to perform the architect's own engagement from amounts merely collected for another vendor. Pause when client contracts call the arrangement consultancy but invoices and purchase records show substantial execution work, when several principals share one project receipt, or when foreign design work and remittances introduce additional disclosure questions.`,

  "ay-2026-27-cash-deposit-ais-review-guide": `## Give every material deposit a source and a cash-position test

Start with a dated deposit register, not the annual AIS total. For each material entry, record the bank account, amount, depositor if known, and the claimed source: recorded cash sales, an earlier withdrawal, asset proceeds, loan, gift, household transfer, or another event. Then test whether cash was actually available between the source event and deposit date after considering spending and other deposits. A matching round amount is only a clue; it is not enough to prove that withdrawn cash returned to the bank.

The filing decision should separate three buckets: deposits already represented in reported income or turnover, supported capital movements, and amounts that remain unexplained. For a cash-heavy business, compare deposits with daily sales, cash expenses, and the cash book rather than relying on annual sales alone. For family transfers or loans, identify the counterparty and the record that supports the movement. Do not force every deposit into income, but do not use labels such as redeposit or gift where the chronology cannot support them.`,

  "ay-2026-27-co-owned-house-property-itr-guide": `## Agree the owner-level property computation before anyone files

Create one common schedule for the property, then show each co-owner's allocation. The schedule should identify the ownership basis, share, use during the year, rent entitlement, rent received, municipal tax payment, loan borrower, supported interest, and tenant TDS. A tenant may pay the full rent into one account, and a lender may debit only one borrower, without changing the allocation supported by the ownership and payment facts. Record those collection arrangements so they are not mistaken for a different beneficial share.

Resolve differences between co-owners before their separate returns are prepared. Compare whether everyone is treating the property as let out or self-occupied for the same periods, whether vacancy and arrears are consistently recorded, and whether the combined rent, interest, and TDS equal the common schedule. If one owner claims a different share or interest amount, write the factual reason beside it. Stop for review where the deed, family arrangement, actual contribution, or rent entitlement points in different directions, because a convenient equal split may create incompatible returns.`,

  "ay-2026-27-donation-deduction-record-guide": `## Test the donee and donor record before valuing the claim

Build a donation row that connects the taxpayer, donee, payment date, amount, mode, receipt number, and details shown by the donee for deduction review. Treat the bank debit and receipt as separate evidence: the debit shows money moved, while the receipt identifies the donation the organisation recorded. A name, PAN, date, or amount mismatch should be corrected by the donee instead of being silently adjusted in the return working.

Only after the record is coherent should the deduction amount be considered. Keep different donations separate because their treatment may depend on the donee and the taxpayer's complete computation; do not apply one assumed percentage to a mixed annual total. Confirm that the proposed claim belongs to the taxpayer who paid and is available under the selected regime. Political appeals, crowdfunding messages, event tickets, membership payments, and general acknowledgements should not be called donations without checking what the payment actually bought or supported. Where current donee details or an adequate receipt cannot be verified, leave the amount out of the claim and retain the query trail.`,

  "ay-2026-27-ecommerce-seller-itr-gst-checklist": `## Reconstruct sales before reading the marketplace settlement

Choose one settlement cycle and trace it from customer orders to the bank. Show completed sales, cancellations, returns, discounts funded by each party, GST components, marketplace fees, shipping adjustments, reserves, TCS or TDS, and the final settlement. That bridge reveals whether the platform report is presenting gross merchandise activity, recognised seller sales, or cash movement. Apply the proven method month by month and keep each marketplace separate until its figures reconcile.

The tax-return decision should use supported business sales and expenses, not the amount deposited by the platform. Compare the completed bridge with invoices, GST summaries, inventory or purchase records, AIS, Form 26AS, and bank receipts. Mark timing differences where a sale, return, tax entry, and settlement occur in different periods. Investigate negative settlements and reserve releases instead of netting them into sales without explanation. Pause where accounts operate under another entity or GST registration, where personal purchases appear in seller exports, or where a marketplace no longer provides the underlying order data needed to reproduce the annual total.`,

  "ay-2026-27-esop-sale-perquisite-itr-checklist": `## Reconcile share quantities before calculating the ESOP sale

Prepare an award ledger for each grant. Track shares granted, vested or exercised, withheld or sold for payroll tax, delivered to the broker, transferred, sold later, and still held. Connect the employment event to payslips and Form 16, then connect each later disposal to the broker confirmation. Quantity gaps often reveal forfeitures, sell-to-cover transactions, or transfers that a value-only reconciliation misses.

Once the share trail balances, carry the supported employment-event value and acquisition date into the sale working rather than accepting an unsupported broker cost. Keep salary perquisite, sale proceeds, dividends, and foreign withholding as separate items even when they appear on one platform statement. For foreign plans, review the account and remaining shares independently from the capital-gain calculation; an immediate sale does not prove that no foreign holding or cash balance existed during the relevant period. Pause if historical award statements are missing, payroll and broker values cannot be connected, or shares moved between brokers without a complete cost and quantity trail.`,

  "ay-2026-27-first-time-salaried-employee-itr-guide": `## Make the first return a reusable source-of-income map

Begin with a one-page list of income and tax-credit sources rather than opening a salary-only form immediately. Record the employer, gross salary, payroll exemptions and deductions, TDS, every bank that paid interest, investments sold, freelance or rent receipts, and unexplained AIS entries. Compare Form 16 with payslips, Form 26AS, and the final salary credit pattern, but remember that payroll usually knows nothing about income earned elsewhere.

Use the completed list to choose the form and regime and to calculate the final liability. An expected refund shown by payroll should survive only if all other income, supported claims, and tax credits are included. Investigate AIS entries that belong to another person or duplicate a transaction, while retaining income supported by the taxpayer's own records even if AIS omits it. Before submission, check the assessment year, PAN, refund bank account, payment challan if any, and e-verification route. Preserve the computation and acknowledgement as next year's opening reference instead of leaving the first filing scattered across downloads.`,

  "ay-2026-27-fno-loss-carry-forward-trader-guide": `## Prove the F&O loss and the route that preserves it

Recalculate the result from complete broker tradebooks and ledgers. Keep each broker separate until realised profit or loss, charges, open positions, and bank transfers reconcile, then document the turnover method used. Gross contract value, a dashboard loss, and net cash withdrawn answer different questions. Separate derivatives from delivery investing and intraday equity so the business, speculative, and capital records do not collapse into one figure.

After the trading result is supportable, decide what is required to report and preserve the loss. Connect claimed expenses to the trading activity, review the books and audit question from the actual figures, and identify the correct return schedules. The filing date is part of the loss decision, not an administrative afterthought; record any delay or unresolved audit issue before assuming an amount will remain available for future set-off. The final note should show current-year set-off, proposed carry-forward, and the source of each figure. Escalate missing trade history, incompatible broker reports, unexplained ledger balances, or large losses whose turnover calculation cannot be independently reproduced.`,

  "ay-2026-27-form-16-missing-itr-guide": `## Rebuild gross salary without inventing the missing certificate

Create a month-by-month payroll table from the employment letter, payslips, annual payroll statement if available, bank credits, reimbursements, arrears, perquisites, and joining or exit records. Reconcile net pay to the bank only after gross pay and payroll deductions are understood. A repeated bank credit cannot simply be multiplied by twelve because bonuses, unpaid leave, reimbursements, and withholding can change the relationship.

Compare the reconstructed salary and any TDS with AIS and Form 26AS. Claim only a credit that is reported under the taxpayer's PAN, while separately retaining requests for the employer to issue Form 16 or correct its filing. The missing certificate should not hide a second employer, stock compensation, or another income source that changes the form. Before filing, write down which figures are directly supported, which were derived from payroll records, and which employer issue remains open. Pause if gross salary cannot be reconciled, salary components are disputed, or the proposed tax credit depends only on a payslip deduction that never reached the tax-credit statement.`,

  "ay-2026-27-freelancer-gst-turnover-income-tax-turnover": `## Explain why the freelancer's four annual totals differ

Build an invoice register that separates fee before GST, GST charged, credit notes, reimbursements, TDS, platform fees, collection date, and outstanding balance. From that register, calculate distinct totals for GST reporting, professional income review, TDS-reported gross amounts, and bank collections. Differences may arise from timing, tax components, advances, refunds, or withholding, but every material difference should trace to a client or invoice instead of being explained only by a year-end plug.

Use the reconciled activity to decide the income-tax treatment and form. Keep foreign-client receipts, mixed business activities, and money collected for another person outside the ordinary domestic-fee bridge until their facts are settled. If a client reported the wrong TDS amount or PAN, preserve the correction request rather than changing the invoice total to match Form 26AS. Likewise, do not alter income-tax receipts merely to imitate a GST summary. Pause when invoices cannot be connected to the same service trail, when personal and business receipts share an unexplained account, or when the proposed presumptive approach does not fit the freelancer's actual work.`,

  "ay-2026-27-government-employee-hra-lta-itr-checklist": `## Review HRA and LTA as two unrelated evidence decisions

For HRA, prepare a residence timeline showing the rented address, period, rent obligation, payments, landlord details available, and the salary components used in the payroll calculation. Compare that result with the exemption shown in Form 16. A transfer, government accommodation period, shared rent, or payment to a related person needs a clear chronology rather than a single annual rent total.

For LTA, build a separate journey note identifying the travel event, travellers, dates, route, fare evidence, and amount considered by the employer. Do not mix hotel, food, local sightseeing, or general leave spending into the fare record merely because they belong to the same trip. After both notes are complete, test the final regime and return position; payroll acceptance does not settle what remains supportable in the filed return. Record any difference from Form 16 and the evidence behind it. Pause where residence evidence conflicts with payroll, travel records are incomplete, or a claim depends on assumptions about family travel or reimbursement that the source documents do not establish.`,

  "ay-2026-27-gratuity-tax-checklist-employees": `## Split the final settlement before reviewing gratuity

Start with the settlement letter and bank receipt, then separate gratuity from leave encashment, salary arrears, bonus, provident-fund amounts, reimbursements, and any other payment. Obtain the employer's gratuity calculation and record the service period, pay components used, gross gratuity, amount treated by payroll, TDS, and net settlement. A single narration such as final settlement cannot support the tax treatment of each component.

Reproduce the gratuity calculation from the employer's stated facts before deciding whether a different return figure is supportable. Keep multiple employments and earlier gratuity receipts visible because the current employer's statement may not present the taxpayer's complete history. If service dates, covered status, pay basis, or the amount shown in Form 16 differs from the settlement record, seek clarification and retain the response. The filing note should show gross gratuity, the supported treatment applied, and the remaining taxable settlement items separately. Stop where the employer cannot explain its calculation, service periods overlap, or the proposed position relies on an amount inferred only from the bank credit.`,

  "ay-2026-27-high-value-transaction-ais-checklist": `## Classify the high-value event before deciding its return effect

Create one investigation row for each material AIS entry. Identify the reporting entity, transaction type, gross amount, date or period, taxpayer ownership, and the source record that explains it. A property purchase, securities sale, mutual-fund investment, remittance, card payment, and cash deposit require different questions; none becomes taxable income merely because AIS displays a large number.

Trace genuine transactions to contracts, broker reports, acquisition records, or bank movements, then calculate only the relevant income, gain, disclosure, or capital explanation. Mark duplicate entries, cancellations, joint transactions, and records belonging to another person without deleting the review trail. If feedback is submitted, retain the AIS version and acknowledgement used. The return-form decision should be revisited when the event introduces capital gains, business activity, foreign assets, or another schedule unavailable in the initially expected form. Pause for missing acquisition cost, disputed ownership, unexplained funding, or a transaction whose gross value can be identified but whose actual tax treatment cannot yet be supported.`,

  "ay-2026-27-job-change-two-form-16-itr-checklist": `## Combine two payroll stories into one annual salary result

Build a salary schedule with a column for each employer and a timeline of employment dates. Compare gross salary, exemptions, perquisites, deductions considered, regime assumption, TDS, and final-settlement items. Two employers can each calculate withholding reasonably from incomplete information while the combined return still shows duplicated claims or a balance payable. Overlapping dates also deserve an explanation rather than automatic addition.

Reconcile both Form 16s with payslips, bank credits, AIS, and Form 26AS. Check whether the later employer considered earlier salary and whether either payroll used claims that do not fit the final regime. Remove only genuine duplication; do not drop a salary or tax-credit entry simply because the combined total looks unexpectedly high. If TDS is missing or under the wrong PAN, keep the employer correction trail separate from the supported salary computation. The final review should explain the annual salary, available credits, and any tax payment before filing. Pause where one certificate is missing, employment periods conflict, or a settlement component cannot be assigned to the correct employer and period.`,

  "ay-2026-27-landlord-rental-income-tds-itr-guide": `## Let the lease ledger lead the rental computation

Prepare a separate ledger for every property and tenant. Record the owner, lease period, rent due, rent received, arrears, vacancy, deposit, reimbursement, municipal tax, payment date, and bank account. Keep refundable deposits and expense reimbursements outside rent unless the agreement and later use support another conclusion. Where the tenant deducts tax, show gross rent, TDS, and net receipt as linked but distinct amounts.

Match the ledger to the agreement, tenant certificate, Form 26AS, AIS, and bank trail. A missing or wrong-PAN tenant credit should trigger a correction request, not a reduction of gross rent. Connect loan interest to the same owner, property, borrowing purpose, and period before considering it in that property's working. Co-owned, mixed-use, or partially vacant properties need explicit allocation notes so all periods are visible. The final decision file should explain each material gap between rent due, cash received, and tax reported by the tenant. Pause for disputed ownership, substantial unreconciled arrears, or interest that cannot be tied to the property under review.`,

  "ay-2026-27-lawyer-legal-consultant-itr-guide": `## Separate earned legal fees from money handled for a matter

Review engagement letters and client ledgers before using bank receipts as professional income. Split retainers, appearance or advisory fees, court-fee advances, filing charges, reimbursable travel, client money held temporarily, and amounts belonging to chambers or a firm. For each fee, bridge the invoice or ledger amount to Form 16A and the net client payment after TDS. This makes it possible to identify gross professional receipts without treating every client-related transfer as earned income.

Use the resulting practice map to decide the return route, expense treatment, and any presumptive question. A lawyer working through a firm, independently, and for foreign clients may need separate streams rather than one occupation label. Test expenses against the actual practice responsibility; a cost paid from the account is not automatically the lawyer's own expense when it was recoverable from a client or borne for another advocate. Pause where trust-like client balances are mixed with fees, chamber allocations are undocumented, foreign receipts lack contracts, or the client and lawyer classify the same payment differently.`,

  "ay-2026-27-medical-disability-deduction-family-checklist": `## Identify the claimant, covered person, and evidence route

Start by naming the taxpayer who would claim, the person whose disability or medical condition is relevant, their relationship, and any dependency fact needed for the proposed route. Keep the prescribed certificate or other required record separate from general treatment bills, insurance premiums, and medicine expenses. Those documents describe different facts and should not be pooled into one medical total. Record the certificate's name, issuer, date, and validity information exactly as shown, while limiting circulation of unrelated clinical details.

Then decide which specific claim, if any, the available evidence supports under the selected regime. Check whether another family member is proposing a claim for the same person or payment, and resolve that overlap before filing. A large medical spend does not establish a disability claim, while a certificate does not automatically support every treatment expense. Where names, relationship records, dependency facts, or certificate status are unclear, leave the proposed amount open for a review of those specific records. The retained file should contain only the records needed to explain the conclusion, protecting privacy without making the claim impossible to verify.`,

  "ay-2026-27-minor-child-income-clubbing-checklist": `## Trace each child's income back to the asset and funding source

List every income-producing account or asset held for the minor: deposits, mutual funds, shares, property interests, or work-related receipts. For each one, record who funded or transferred the asset, who controls it, the income earned, and where the money was credited. The closing balance and the child's bank-interest total do not reveal whether the income arose from a family gift, inherited asset, reinvestment, or the child's own activity.

Use that source map to decide whether an amount belongs in a parent's computation or needs separate treatment. Keep income from the child's own skill, work, or performance visible rather than grouping it with passive investment income. If both parents may be relevant, compare the family and prior-return facts before selecting the reporting position, and document any change from earlier years. Later reinvestment should remain linked to its original source so accumulated income is not mistaken for new independent funding. Pause for changing custody, disputed beneficial ownership, foreign accounts, or pooled family investments where the child's units and income cannot be reliably identified.`,

  "ay-2026-27-nps-80ccd1b-deduction-checklist": `## Allocate NPS contributions by payer before entering deductions

Build a contribution schedule from the PRAN statement, bank trail, and Form 16. Separate amounts paid personally by the taxpayer, amounts deducted from salary, and amounts contributed by the employer. Also record transaction dates and reversals so a statement total is not copied into one deduction line when it represents several contribution sources or periods.

Use the schedule to test the final regime and the proposed treatment of each contribution category. Confirm that a personal bank debit and payroll deduction are not the same contribution appearing twice, and investigate employer amounts shown in one source but absent from another. If the PRAN, taxpayer identity, or contribution period is wrong, seek correction before relying on the entry. The decision note should explain which amount is being considered under each part of the computation and why, without assuming the entire annual statement is available as an additional claim. Pause where contributions were reversed, posted outside the relevant period, split across PRANs, or funded by another person without a clear record of who is entitled to claim them.`,

  "ay-2026-27-overseas-remittance-tcs-itr-checklist": `## Separate the remittance purpose from the TCS credit

Prepare a remittance register showing the payer, beneficiary, purpose, bank or collector, date, gross remittance, TCS, cancellation or refund, and PAN used by the collector. Family payments and education or medical remittances can involve several people, so identify whose tax-credit statement should contain each entry. A TCS amount proves that tax was collected and reported; it does not decide whether the remittance itself is income, an expense, or a deduction.

Match each credit to the remittance advice, collector certificate, Form 26AS, and AIS. Where the PAN, amount, or period is wrong, preserve the bank correction request and claim only the credit that can be supported in the taxpayer's current records. Calculate the full return before treating TCS as a refund: the credit offsets final liability and does not independently guarantee money back. Review what the remittance created or funded, such as a foreign account, investment, or education payment, because that may raise a separate disclosure or evidence question. Pause for credits split between family members, reversals not reflected by the collector, or a refund driven mainly by unreconciled TCS.`,

  "ay-2026-27-pensioner-family-pension-itr-guide": `## Label every retirement receipt before combining annual income

Create an institution-level register that separates pension, family pension, commuted or arrear payments, bank interest, and any other retirement-related receipt. Record the payer, recipient, gross amount, TDS, period, and bank account. A bank may describe several credits as pension, while a family-pension payment and the taxpayer's own pension can require different handling. Likewise, the net amount deposited after TDS is not the gross income figure.

Compare payer certificates and bank statements with AIS and Form 26AS, then investigate missing or duplicate credits. Keep each bank's interest separate, including deposits linked to the pension account, so interest is not omitted merely because the account is used for pension. For arrears or commutation, retain the payer's breakup and do not infer the components from one large credit. The final review should show the nature of each receipt, the supported tax credits, and any refund or payment from the complete computation. Pause for inherited or joint accounts, several pension payers, or a payment whose description does not establish whether it belongs to the pensioner or a deceased family member.`,

  "ay-2026-27-representative-filing-deceased-taxpayer-checklist": `## Keep authority to act separate from the deceased person's tax facts

Build two connected records. The authority record should contain the death document, representative or legal-heir basis, portal status, and correspondence that permits action. The tax record should contain the deceased taxpayer's PAN, income, deductions, tax credits, prior returns, bank details, and outstanding proceedings. Access to an account does not prove authority to file, and recognised authority does not make an incomplete income record reliable.

Prepare a dated chronology around the death and the filing period. Identify which income and transactions belong to the deceased person, which occurred later, and which accounts remain in that person's name. Confirm that any refund bank detail is supportable and not selected merely because a representative controls it. Keep portal responses and submitted acknowledgements because status and access can change during follow-up. Pause for competing representatives, inaccessible broker or bank records, foreign assets, disputed refund ownership, or material income whose timing around the date of death cannot be established. Those issues should remain explicit rather than being resolved through assumptions made only to complete the portal filing.`,

  "ay-2026-27-resident-foreign-asset-disclosure-checklist": `## Map each foreign holding to its disclosure and income questions

Create one inventory row per foreign bank account, broker account, employer share plan, company interest, property, pension, or other asset. Record country, institution, ownership basis, opening and closing dates, statements available, income, withholding, sale activity, and the values needed for review. A year-end screenshot cannot establish ownership throughout the period, peak or other requested values, income earned, or acquisition cost.

For each row, separately answer whether it creates an asset disclosure, foreign-income entry, tax-relief question, or capital-gain calculation. Link those workings without combining them; reporting an account does not report its income, and reporting a sale does not settle the remaining holding. Explicitly review dormant, joint, beneficially owned, inherited, and employer-linked accounts. Preserve the original statements and the exchange-rate method used so values can be reproduced. Pause where residential status is uncertain, historical reports are unavailable, an old employer account remains accessible but unexplained, or ownership cannot be distinguished from mere signing authority. Do not omit the row or invent a value simply to complete a schedule field.`,

  "ay-2026-27-rnor-foreign-income-review-guide": `## Decide residence first, then classify every foreign item

Complete the residential-status working from travel, passport, employment, and other relevant history before reviewing foreign receipts. Then inventory foreign salary, business activity, investment income, gains, accounts, assets, and remittances. For every item, record where it arose, where it was received, who owned or controlled it, and the activity behind it. The RNOR label alone does not answer those questions, and a foreign bank location does not settle the source of income.

Write a short inclusion, exclusion, or disclosure conclusion beside each material item. Keep transfers of earlier savings separate from current income, and review businesses controlled from India independently from passive foreign holdings. The same statement may support an income question and an asset question, but those conclusions should remain distinct. Retain the day-count calculation, contracts, statements, withholding records, and exchange-rate working that support the final position. Pause for split-year facts, remote work performed in several countries, uncertain business control, large remittances with no source trail, or accounts whose beneficial owner cannot be established.`,

  "ay-2026-27-salary-without-tds-itr-guide": `## Calculate the salary liability without assuming a tax credit

Reconstruct gross salary month by month from the employment agreement, payslips, annual payroll information, bank credits, reimbursements, perquisites, arrears, and final settlement. Record why no TDS appears and whether the employer's payroll is complete. Net credits cannot establish gross salary, and the absence of TDS does not remove the income from the return.

Add every other income source before comparing regimes and calculating the final liability. Then decide whether payment and interest questions need attention from the complete computation, not from the employer's zero-withholding position. If payroll records are incomplete or the employer should correct reporting, retain the correspondence but do not invent a Form 26AS credit or reduce salary to fit available cash. The form choice should reflect capital gains, freelance receipts, foreign assets, and other facts beyond salary. Preserve the salary reconstruction and any challans with the filed return. Pause where perquisites are unreported, multiple employers used different records, foreign salary is involved, or the payment timing and interest calculation remain unresolved.`,

  "ay-2026-27-self-occupied-home-loan-interest-checklist": `## Connect the loan interest to ownership, purpose, and use

Start with the ownership record, loan sanction and account, annual interest certificate, and a timeline for purchase, construction, possession, and use. Separate interest, principal, fees, insurance, and other charges instead of copying the EMI total. For a joint loan, show each borrower's payment and each owner's share; being named on the loan does not by itself explain who owns the property or what share is supportable.

Use the timeline to decide how the interest should be reviewed for the year. Confirm that the borrowing funded the same property and that refinancing or top-up amounts are traced to their actual use. If the home was let out, vacant, under construction, or self-occupied for only part of the period, keep those facts visible rather than applying one annual label. Compare the final position under the selected regime and retain the certificate and allocation working. Pause where possession dates are unclear, pre-construction interest has not been separated, joint owners propose incompatible shares, or a lender certificate combines loans that relate to different properties or purposes.`,

  "ay-2026-27-senior-citizen-bank-interest-tds-itr": `## Reconcile interest by deposit, owner, and tax credit

Prepare an institution-level schedule covering savings accounts, fixed and recurring deposits, bonds, post-office records, sweep arrangements, and pension-linked accounts. For each item, record the holder, interest period, gross interest, TDS, maturity or renewal movement, and certificate source. Net bank credits and renewed principal can obscure the interest actually reported, while joint accounts can cause the same amount to be assumed by more than one person.

Compare the schedule with Form 16A, AIS, Form 26AS, and account statements. Investigate interest or TDS that appears in only one source, but keep the income calculation separate from the tax-credit correction. A declaration given to the bank may explain withholding behavior; it does not remove taxable interest from the return. Review any deduction claim and refund only after total income and supported credits are complete. Where an account belongs beneficially to another holder or arose through inheritance, document the ownership conclusion. Pause for wrong-PAN TDS, unexplained credits, duplicate joint-account reporting, or certificates that cannot separate principal movements from interest.`,

  "ay-2026-27-small-shop-44ad-presumptive-itr-guide": `## Test the shop's actual receipts before choosing presumptive treatment

Build a sales and collection summary from bills, daily records, GST information where applicable, bank deposits, digital-payment reports, and cash on hand. Separate sales from owner capital, loans, supplier refunds, and other deposits. Also distinguish cash and non-cash receipts where the proposed computation depends on payment mode. Presumptive treatment does not make an unexplained bank deposit part of turnover or erase the need to establish what the shop actually sold.

Describe every activity carried on through the premises or accounts. Retail sales, commission income, agency collections, repair services, delivery-platform receipts, and another family business should not be merged solely because they share a counter. Use that activity map and supported turnover to decide whether the proposed route and form fit the complete profile. Compare the presumptive result with available records and retain the reconciliation even if detailed expenses are not used in the computation. Pause near a relevant statutory condition, where losses or foreign assets exist, or where GST, sales records, and deposits cannot be connected without unexplained balancing entries.`,

  "ay-2026-27-spouse-income-clubbing-checklist": `## Follow the transferred asset until it produces income

Create a transfer trail showing the original asset or money, transfer date, consideration if any, receiving spouse, asset later acquired, and income produced. Keep the receiving spouse's independent funds separate from transferred funds, especially where both move through a joint account. Joint account access does not establish beneficial ownership, and a gift description does not by itself connect a later dividend, rent, interest, or gain to that transfer.

For every income item under review, write whether it came directly from the transferred asset, from a later reinvestment, or from the recipient's independent property. Preserve the sequence across years so a sale and reinvestment do not break the explanation. Compare both spouses' records and proposed returns before filing; the same income should not be omitted by one and treated as independent by the other. Business interests, salary-like payments, and assets acquired with mixed funding require their own factual analysis rather than a family-wide assumption. Pause where consideration is disputed, ownership records conflict, foreign assets are involved, or the trail cannot distinguish transferred capital from later independent additions.`,

  "ay-2026-27-startup-founder-salary-dividend-itr-guide": `## Classify every founder-company movement before reconciling tax forms

Build a ledger of all amounts moving between the founder and company: salary, director remuneration, dividend, reimbursement, loan, capital contribution, share issue, option benefit, share sale, and personal payment through company accounts. Link each entry to payroll, board or shareholder approval, cap table, company ledger, invoice, agreement, or sale record. Bank narrations such as transfer, expenses, or founder do not settle classification.

After the ledger is complete, reconcile Form 16, Form 16A, AIS, and Form 26AS with both the founder's and company's records. Keep genuine reimbursements distinct from personal expenses, and keep equity events separate from salary even when they happen near the same funding round. A classification chosen only for one return can create an incompatible company-side record. Review foreign shares, investors, and accounts independently where present. Pause for related-party balances with no agreement, unrecorded founder-paid expenses, disputed cap-table entries, or amounts the company treats as a loan while the founder treats them as income or repayment. Resolve those differences at source before filing.`,

  "ay-2026-27-youtube-creator-income-itr-guide": `## Build the creator's revenue picture beyond platform payouts

List each revenue channel separately: platform advertising, sponsorships, affiliate commissions, subscriptions, licensing, events, consulting, foreign payouts, and barter or gifted products. For every channel, record the gross statement or invoice value, platform fee, withholding, currency conversion, GST component where relevant, net receipt, and amount still outstanding. A bank payout may combine several periods or exclude fees, while a free product may require a factual review even though no cash arrived.

Reconcile platform exports, brand contracts, invoices, Form 16A, AIS, Form 26AS, payment-service accounts, and bank receipts. Keep personal purchases outside the activity record and connect claimed production, editing, equipment, travel, or team costs to the content business. Separate foreign payment accounts and unsold gifted items from ordinary cash receipts so disclosure and valuation questions remain visible. Use the completed activity map to decide the return form, books, presumptive question, and treatment of mixed income streams. Pause where sponsorships lack contracts, platform history is unavailable, or personal and business use of major equipment cannot be reasonably distinguished.`,
};
