import React, { useRef } from "react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Download, Share2, Copy, Check, FileText, Image } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface CalculatorExportProps {
  title: string;
  data: Record<string, string | number>;
  resultRef?: React.RefObject<HTMLDivElement>;
}

export function CalculatorExport({ title, data, resultRef }: CalculatorExportProps) {
  const { toast } = useToast();
  const [copied, setCopied] = React.useState(false);

  // Format data as text for sharing/copying
  const formatAsText = () => {
    const lines = [
      `📊 ${title}`,
      `Generated by MyeCA.in`,
      `Date: ${new Date().toLocaleDateString('en-IN')}`,
      ``,
      ...Object.entries(data).map(([key, value]) => {
        const formattedValue = typeof value === 'number' 
          ? `\u20B9${value.toLocaleString('en-IN')}`
          : value;
        return `${key}: ${formattedValue}`;
      }),
      ``,
      `Calculate your taxes at https://myeca.in/calculators`
    ];
    return lines.join('\n');
  };

  // Copy to clipboard
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(formatAsText());
      setCopied(true);
      toast({
        title: "Copied!",
        description: "Results copied to clipboard",
      });
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast({
        title: "Copy failed",
        description: "Please try again",
        variant: "destructive",
      });
    }
  };

  // Share via Web Share API
  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: title,
          text: formatAsText(),
          url: window.location.href,
        });
        toast({
          title: "Shared!",
          description: "Results shared successfully",
        });
      } catch (err) {
        // User cancelled or error
        if ((err as Error).name !== 'AbortError') {
          toast({
            title: "Share failed",
            description: "Please try copying instead",
            variant: "destructive",
          });
        }
      }
    } else {
      // Fallback to copy
      handleCopy();
    }
  };

  // Download as PDF (using print to PDF)
  const handleDownloadPDF = () => {
    // Create a printable version
    const printContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title} - MyeCA.in</title>
          <style>
            :root {
              --text-xs: 0.75rem;
              --text-sm: 0.875rem;
              --text-base: 1rem;
              --text-lg: 1.125rem;
              --text-xl: 1.25rem;
              --text-2xl: 1.5rem;
              --text-3xl: 1.875rem;
              --leading-normal: 1.5;
            }
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { 
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
              padding: 40px; 
              color: #1f2937;
              line-height: var(--leading-normal);
            }
            .header { 
              text-align: center; 
              margin-bottom: 30px; 
              padding-bottom: 20px;
              border-bottom: 2px solid #e5e7eb;
            }
            .logo { 
              font-size: var(--text-2xl); 
              font-weight: bold; 
              color: #1e40af;
              margin-bottom: 5px;
            }
            .title { 
              font-size: var(--text-3xl); 
              font-weight: bold; 
              color: #111827;
              margin-bottom: 10px;
            }
            .date { 
              color: #6b7280; 
              font-size: var(--text-sm); 
            }
            .results { 
              background: #f9fafb;
              border-radius: 12px;
              padding: 24px;
              margin: 20px 0;
            }
            .result-row { 
              display: flex; 
              justify-content: space-between; 
              padding: 12px 0;
              border-bottom: 1px solid #e5e7eb;
            }
            .result-row:last-child { border-bottom: none; }
            .result-label { color: #4b5563; }
            .result-value { 
              font-weight: 600; 
              color: #111827;
            }
            .highlight {
              background: linear-gradient(135deg, #1e40af 0%, #3b82f6 100%);
              color: white;
              padding: 20px;
              border-radius: 12px;
              margin-top: 20px;
            }
            .highlight .result-label { color: #bfdbfe; }
            .highlight .result-value { color: white; font-size: var(--text-2xl); }
            .footer { 
              text-align: center; 
              margin-top: 40px; 
              padding-top: 20px;
              border-top: 1px solid #e5e7eb;
              color: #6b7280;
              font-size: var(--text-xs);
            }
            .disclaimer {
              background: #fef3c7;
              border: 1px solid #f59e0b;
              border-radius: 8px;
              padding: 12px;
              margin-top: 20px;
              font-size: var(--text-xs);
              color: #92400e;
            }
            @media print {
              body { padding: 20px; }
              .no-print { display: none; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="logo">MyeCA.in</div>
            <div class="title">${title}</div>
            <div class="date">Generated on ${new Date().toLocaleDateString('en-IN', { 
              weekday: 'long', 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })}</div>
          </div>
          
          <div class="results">
            ${Object.entries(data).map(([key, value], index, arr) => {
              const formattedValue = typeof value === 'number' 
                ? `\u20B9${value.toLocaleString('en-IN')}`
                : value;
              const isLast = index === arr.length - 1;
              return isLast 
                ? `</div><div class="highlight"><div class="result-row"><span class="result-label">${key}</span><span class="result-value">${formattedValue}</span></div></div>`
                : `<div class="result-row"><span class="result-label">${key}</span><span class="result-value">${formattedValue}</span></div>`;
            }).join('')}
          
          <div class="disclaimer">
            <strong>Disclaimer:</strong> This calculation is for informational purposes only. 
            Actual tax liability may vary. Please consult a tax professional for accurate tax advice.
          </div>
          
          <div class="footer">
            <p>Calculate your taxes at <strong>myeca.in</strong></p>
            <p>India's trusted tax filing platform</p>
          </div>
        </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.onload = () => {
        printWindow.print();
      };
    }
    
    toast({
      title: "PDF Ready",
      description: "Use your browser's print dialog to save as PDF",
    });
  };

  // Download as text file
  const handleDownloadText = () => {
    const text = formatAsText();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    if (a.parentNode) a.remove();
    URL.revokeObjectURL(url);
    
    toast({
      title: "Downloaded!",
      description: "Results saved as text file",
    });
  };

  return (
    <div className="flex items-center gap-2">
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" size="sm" className="gap-2">
            <Download className="h-4 w-4" />
            <span className="hidden sm:inline">Download</span>
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onClick={handleDownloadPDF} className="gap-2 cursor-pointer">
            <FileText className="h-4 w-4" />
            Save as PDF
          </DropdownMenuItem>
          <DropdownMenuItem onClick={handleDownloadText} className="gap-2 cursor-pointer">
            <FileText className="h-4 w-4" />
            Save as Text
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" size="sm" className="gap-2">
            <Share2 className="h-4 w-4" />
            <span className="hidden sm:inline">Share</span>
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onClick={handleShare} className="gap-2 cursor-pointer">
            <Share2 className="h-4 w-4" />
            Share Results
          </DropdownMenuItem>
          <DropdownMenuItem onClick={handleCopy} className="gap-2 cursor-pointer">
            {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
            {copied ? "Copied!" : "Copy to Clipboard"}
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}

// Simple export buttons for inline use
export function ExportButtons({ title, data }: CalculatorExportProps) {
  return <CalculatorExport title={title} data={data} />;
}

